### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by K4KDR** [m0iax/JS8CallUtilsGPSD#1]
Thank you for such a useful utility!!

After installing the listed dependencies (plus 'pip3 install gps'), the correct grid is obtained from the GPS.

However, I get the following when attempting to send that to JS8CALL  (updated UDP port in js8call.cfg to match value in JS8CALL).

Thanks!

-Scott,  K4KDR

```
pi@K4KDR-DRAWS:~/JS8CallUtilsGPSD $ ./js8callutilsGPSD.py
Getting Grid from GPS
Sending Grid to JS8CAll... FM17es66
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1562, in __call__
    return self.func(*args)
  File "./js8callutilsGPSD.py", line 236, in <lambda>
    self.setJS8CallGridButton = tk.Button(lowerFrame, text="Send Grid to JS8Call", command=lambda: self.sendGridToJS8Call(self.gridrefEntry.get()), bg="white", font=40)
  File "./js8callutilsGPSD.py", line 421, in sendGridToJS8Call
    self.sendMessageAndClose(TYPE_STATION_SETGRID, gridText)
  File "./js8callutilsGPSD.py", line 402, in sendMessageAndClose
    message = json.loads(content)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

**Comment by m0iax** [comment]
Hi Scott,

That’s really odd. I’ve not seen any similar problems recently. I will look into it as soon as I can.
Can you let me know what Operating System and version of the OS you are using?

Ive got the same code running on Raspbian Buster and Windows, that looks like an error I saw when I started figuring out this code early last year but not seen since.
Also what version of JS8Call are you using?

Thanks for your input.

Cheers

Mark
M0IAX

**Comment by m0iax** [comment]
Hi Again Scott, it turns out it was a fairly simple fix. The piece of code where the error is coming from isn’t required any more in this app as we don’t need to read from the JS8 API just send to it.

Please pull the latest from github and try again, it should work

73
Mark

**Comment by K4KDR** [comment]
Thank you so much!!

To answer your first questions:

```
pi@K4KDR-DRAWS:~/JS8CallUtilsGPSD $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
```
... and JS8CALL is v2.1.1

Works great now, but only after I changed '**gpscomport**' in **gps.cfg** from '**COM8**' to '**/dev/gps0**'

```
pi@K4KDR-DRAWS:~/JS8CallUtilsGPSD $ ./js8callutilsGPSD.py
Getting Grid from GPS
Sending Grid to JS8CAll... FM17es66
sending outgoing message: {"value": "FM17es66", "type": "STATION.SET_GRID", "params": {"_ID": 1582302443635}}
Sending  @APRSIS GRID FM17es66
sending outgoing message: {"value": "@APRSIS GRID FM17es66", "type": "TX.SEND_MESSAGE", "params": {"_ID": 1582302473636}}
```
