### ISSUE TITLE
not initilizing gps

### ISSUE THREAD

**Issue by GlacialDevelopment** [m0iax/JS8CallUtilsGPSD#2]
I think I've got the problem surrounded for once, instead of vice-versa, still in over my head. the problem is an inadequate nut on the keyboard.

ublox GPS connected at /dev/ttyACM0 and verified sending it's properly formatted NMEA sentences. 

changed gps.cfg from default COM8 to /dev/ttyACM0 

run program, click get grid from gps button, get error "Error initilizing GPS, check com port and restart this app."

**Comment by m0iax** [comment]
This version of the app requires GPSD to be installed and configured on your pi (should also work on other unix based OSs) changine the com port in settings will make no difference in this version, the GPS listener does not check the setting.
There is another version I wrote for Windows users that uses GPS on a serial port, I think it might work on unix with the com port configured. The code will run on linuc and windows so Im sure it will run, you could try that (but I have not been able to test it yet) - https://github.com/m0iax/JS8CallUtilsSerial run it, then set the com port as you have already tried and restart it.

A future version of this app will figure out which option it needs to use.

**Comment by GlacialDevelopment** [comment]
got some errors, not sure how much info is too much so....err on the side of all of it from start to error.  sorry if it's more inadequate nut on keyboard. i -think- i might have an idea how to fix it, but i also know how to break an anvil with a glass hammer, so i'll wait for instructions from somebody who actually knows what's going on.  and considering this is related to the other utility not working in a way it wasn't designed to work, it's not a problem here or there, so should i close this and be patient? 

```

pi@raspberrypi:~ $ pip3 install maidenhead && pip3 install searial && pip3 install configparser && pip3 install gps
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: maidenhead in ./.local/lib/python3.7/site-packages (1.3.0)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting searial
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/searial/

pi@raspberrypi:~ $ pip3 install serial && pip3 install configparser && pip3 install gps
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: serial in ./.local/lib/python3.7/site-packages (0.0.97)
Requirement already satisfied: iso8601>=0.1.12 in ./.local/lib/python3.7/site-packages (from serial) (0.1.12)
Requirement already satisfied: future>=0.17.1 in ./.local/lib/python3.7/site-packages (from serial) (0.18.2)
Requirement already satisfied: pyyaml>=3.13 in ./.local/lib/python3.7/site-packages (from serial) (5.3)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting configparser
  Downloading https://files.pythonhosted.org/packages/7a/2a/95ed0501cf5d8709490b1d3a3f9b5cf340da6c433f896bbe9ce08dbe6785/configparser-4.0.2-py2.py3-none-any.whl
Installing collected packages: configparser
Successfully installed configparser-4.0.2
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: gps in ./.local/lib/python3.7/site-packages (3.19)
pi@raspberrypi:~ $ git clone https://github.com/m0iax/JS8CallUtilsSerial.git
Cloning into 'JS8CallUtilsSerial'...
remote: Enumerating objects: 94, done.
remote: Counting objects: 100% (94/94), done.
remote: Compressing objects: 100% (65/65), done.
remote: Total 94 (delta 53), reused 64 (delta 27), pack-reused 0
Unpacking objects: 100% (94/94), done.
pi@raspberrypi:~ $ ls
Desktop    Downloads    JS8CallUtilsGPSD    MagPi  Pictures  Templates
Documents  export.adif  JS8CallUtilsSerial  Music  Public    Videos
pi@raspberrypi:~ $ cd JS8CallUtilsSerial/
pi@raspberrypi:~/JS8CallUtilsSerial $ sudo chmod +x 
chmod: missing operand after ‘+x’
Try 'chmod --help' for more information.
pi@raspberrypi:~/JS8CallUtilsSerial $ ls
js8callutilsSerial.py  LICENSE  __pycache__  README.md  serialGPSlistener.py
pi@raspberrypi:~/JS8CallUtilsSerial $ sudo chmod +x js8callutilsSerial.py 
pi@raspberrypi:~/JS8CallUtilsSerial $ ls
js8callutilsSerial.py  LICENSE  __pycache__  README.md  serialGPSlistener.py
pi@raspberrypi:~/JS8CallUtilsSerial $ ./js8callutilsSerial.py 
Traceback (most recent call last):
  File "./js8callutilsSerial.py", line 12, in <module>
    import serialGPSlistener
  File "/home/pi/JS8CallUtilsSerial/serialGPSlistener.py", line 9, in <module>
    import serial.tools.list_ports as port_list
ModuleNotFoundError: No module named 'serial.tools'
pi@raspberrypi:~/JS8CallUtilsSerial $ 
```

**Comment by m0iax** [comment]
I have made a change which I think will fix that problem. If you want to grab the latest code and try again, please do. I will test it myself as soon as I get chance to set up a RPi without GPSD to do it.

Mark

**Comment by GlacialDevelopment** [comment]
I hope it wasn't difficult, as i re-read your response, i realized i had not installed and configured gpsd, which i have now done, and now works fine.   sorry for being dumb. but, a at least now i'm little smarter than before. thank you for your patience.
